version: '3.8'

services:
  meal-planner:
    build: .
    container_name: meal-planner
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATA_FILE_PATH=/app/data/tracker_data.json
    volumes:
      - ./data:/app/data
